# Generated by Django 5.2.7 on 2025-12-26 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_alter_affiliateprogram_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateuser',
            name='account_holder',
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Full name as it appears in bank account', max_length=200),
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='bank_details_verified',
            field=models.BooleanField(default=False, help_text='Admin verified bank details are correct'),
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN for tax purposes (optional but recommended)', max_length=10),
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='affiliateuser',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=20),
        ),
        migrations.AlterField(
            model_name='affiliateuser',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the bank (e.g., HDFC Bank, SBI, ICICI)', max_length=100),
        ),
        migrations.AlterField(
            model_name='affiliateuser',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code of the bank branch', max_length=11),
        ),
        migrations.AlterField(
            model_name='affiliateuser',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for quick transfers (e.g., yourname@okhdfcbank)', max_length=255),
        ),
    ]
