# Generated by Django 5.2.7 on 2025-11-21 08:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_rating_alter_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_weight_grams',
            field=models.DecimalField(decimal_places=2, default=Decimal('250.00'), help_text='Weight per unit (in grams) used for live shipping calculations', max_digits=8),
        ),
    ]
